### ISSUE TITLE
Cauldron Crafting for Potions

### ISSUE THREAD

**Issue by nivthefox** [SoSly/MNAWitchcraft#14]
Members of the Coven should be able to craft potions and possibly some items via cauldrons.  Look at mods like Joefoxe's Hexerei, as well as Mana and Artifice's Manaweaving, for examples on how to implement.

At the very basic, this should be a way to craft any item that could be crafted with Manaweaving (a Witch's Cauldron is a variant Manaweaving Altar), as well as a way to craft Potions.   There are probably many other fun things that can be done with a Witch's Cauldron.

The Witch's Cauldron itself will need to be added, and it will require fluid; possibly it will need custom fluid rendering so that the colors can change based on the contents.  

More research is needed, here.

**Comment by Mithion** [comment]
May want to investigate another mod of mine, Mystic Alchemy for cauldron brewing and instead integrate with that.

**Comment by Mithion** [comment]
Come to think of it, it may be neat for Apostates to have more insight into what ingredients do within mystic alchemy

**Comment by nivthefox** [comment]
@Mithion Is there a way to give them that insight?  I'll definitely look into Mystic Alchemy for cauldron brewing; I'd forgotten that was even a thing!  Making this a compat between M&A and Mystic Alchemy sounds like fun. :D

**Comment by Mithion** [comment]
Brewing is just recipes, so absolutely.  On tooltip render (event) look up a recipe and display the effects (I recommend basic caching for subsequent render calls though).  Can even make it that each tier into the coven reveals an additional effect on ingredients!

**Comment by Mithion** [comment]
Unlike M&A, Mystic Alchemy is also open source: https://github.com/Mithion/Mystic-Alchemy 
And upon reading this I realize it also needs an update to 1.20.  No problem.

**Comment by nivthefox** [comment]
Yeah, I also saw it's a version behind. I'd be happy to update it to 1.20 for you in a Pull Request. That'll get me familiar with the mod anyways since I'm going to need to add a way to figure out the other stuff. :)

**Comment by Mithion** [comment]
Sure, if you want.  It's _much_ simpler than M&A so it certainly won't take long.
