### ISSUE TITLE
The Coven of Apostates

### ISSUE THREAD

**Issue by nivthefox** [SoSly/MNAWitchcraft#17]
The Coven of Apostates faction needs to be added  to the game.  This will not include a way to join the faction, but will include the basis for the faction, including its casting resources, and possibly a faction capability.

Ideally, there will also be codex entries related to the faction.  

The Coven of Apostates avoids the faction war, but all of the factions watch them carefully. Coven mages who use a Faction item for another faction incur ire at a far faster rate than other mages.

**Comment by Mithion** [comment]
My suggestion for the casting resource is "Malice"

**Comment by nivthefox** [comment]
I'll need to think on that some.  Malice or Spite are both great words for the traditional witch, but that is at odds with the idea of avoiding the faction war.  (Why would someone full of Malice not hate ALL of the factions?) 

As a side note, I think Witches will not have a means of regenerating their Mana resource without some kind of Regeneration effect (Potion of Mana Regeneration, Mana Tea, or being near a Mana Crystal).

**Comment by Mithion** [comment]
Malice can exist without being wielded against the factions - maybe they have malice for the villagers and such and just haven't had a reason to turn it on the factions yet!

**Comment by nivthefox** [comment]
Probably going to go with "Essence", but also "Malice" if you piss off the factions. Basically going to do this like the fey where there are two sub-factions: Hedge Witches and Dark Witches.

Hedge Witches avoid the faction war.  Dark Witches have pissed off the Factions, but base Minecraft witches like them (adjusted targeting for those).

**Comment by nivthefox** [comment]
Mithion says better to do this with two separate factions, so two it is.
