### ISSUE TITLE
Prevent Targeted Casting inside of Boss Arenas

### ISSUE THREAD

**Issue by Mithion** [SoSly/MNAWitchcraft#26]
Bosses are challenging enough without someone griefing you form half the world away.  Yes, you could counter that with a charm, but that takes away a valuable slot that the boss balancing relies on you having.

For your consideration.

**Comment by nivthefox** [comment]
@Mithion Since you're the guy who would know: How do you detect that someone's in a boss arena?

**Comment by Mithion** [comment]
StructureUtils.isInsideBossArena(BlockPos)
