### ISSUE TITLE
Charm against Sympathetic Magic

### ISSUE THREAD

**Issue by nivthefox** [SoSly/MNAWitchcraft#3]
A new Charm item that can be worn to prevent Sympathetic Magic from working. Each time Sympathetic spells are attempted on the wearer, the charm loses a charge.

Should the wearer be notified when a charge is used, or only when the charm breaks?  I think only when it breaks, so they should pay close attention if they're under attack!

**Comment by Mithion** [comment]
I think when a charge is used.  Without some kind of UI to display on the HUD and how charms are somewhat buried, that's asking a lot in terms of checks.  Plus, knowing you're being targeted puts you in an interesting position.  Do you keep doing what you're doing, or do you run for a safe zone?

Also should probably make some kind of warding candle equivalent that can protect an area more permanently.  Perhaps powered by Eldrin energy?

**Comment by nivthefox** [comment]
![charm_of_protection](https://github.com/SoSly/MNAWitchcraft/assets/848667/2030c028-755e-4235-8422-a7bf3bcf690e)
